export type User = {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  role: string;
  status: string;
  verified: boolean;
  permissions: string[];
};
export type Page<T> = { items: T[]; page: number; size: number; total: number };
export type Bus = {
  id: number;
  registration: string;
  model: string;
  capacity: number;
  type: string;
  features: string;
  status: string;
  openIncidents?: number;
  nextTrip?: {
    id: number;
    departure: string;
    route: string;
    driver: string;
    conductor: string;
  } | null;
};
export type Stop = {
  id?: number;
  name: string;
  latitude: number;
  longitude: number;
  order?: number;
  minutesFromDeparture?: number;
  eta?: string;
};
export type Route = {
  id: number;
  name: string;
  origin: string;
  destination: string;
  distanceKm: number;
  active: boolean;
  imageUrl?: string;
  stops: Stop[];
};
export type Trip = {
  id: number;
  routeId: number;
  origin: string;
  destination: string;
  routeName: string;
  distanceKm: number;
  bus: Bus | null;
  driver: { id: number; name: string; online?: boolean } | null;
  conductor: { id: number; name: string; online?: boolean } | null;
  crewOnline?: boolean;
  departure: string;
  arrival: string;
  durationMinutes: number;
  fare: number;
  status: string;
  availableSeats: number;
  delayMinutes: number;
  gpsAvailable: boolean;
  driverAcknowledged: boolean;
  conductorAcknowledged: boolean;
  stops: Stop[];
};
export type Seat = {
  id: number;
  inventoryId: number;
  number: string;
  row: number;
  column: number;
  type: string;
  position: string;
  status: string;
};
export type Hold = {
  inventoryId: number;
  tripId: number;
  seatId: number;
  seatNumber: string;
  holdToken: string;
  expiresAt: string;
  serverTime: string;
  fare: number;
};
export type Booking = {
  id: number;
  reference: string;
  passengerId: number;
  passengerName: string;
  passengerPhone: string;
  tripId: number;
  origin: string;
  destination: string;
  departure: string;
  arrival: string;
  tripStatus: string;
  bus: string;
  seat: string;
  seatNumber?: string;
  pickupStop?: string;
  dropoffStop?: string;
  status: string;
  totalAmount: number;
  createdAt: string;
  paymentStatus: string;
  paymentReference: string;
  paymentMethod: string;
};
export type Notification = {
  id: number;
  type: string;
  title: string;
  message: string;
  read: boolean;
  createdAt: string;
  role?: string;
  recipientId?: number;
  recipientName?: string;
};
export type SupportRequest = {
  id: number;
  passengerName: string;
  passengerEmail?: string;
  category: string;
  subject: string;
  description: string;
  status: string;
  response: string | null;
  createdAt: string;
};
export type Refund = {
  id: number;
  bookingId: number;
  bookingReference: string;
  passengerName: string;
  reason: string;
  amount: number;
  status: string;
  rejectionReason: string | null;
  attempts: number;
  createdAt: string;
  gatewayReference?: string;
};
export type Incident = {
  id: number;
  busId: number;
  bus: string;
  reportedBy: string;
  type: string;
  category?: string;
  description: string;
  priority: string;
  severity?: string;
  status: string;
  createdAt: string;
};
export type Staff = {
  id: number;
  name: string;
  firstName?: string;
  lastName?: string;
  email: string;
  phone: string;
  role: string;
  status: string;
  available: boolean;
  licenseNumber: string;
  employeeId?: string;
  department?: string;
  nic?: string;
  duties: {
    id: number;
    route: string;
    departure: string;
    arrival: string;
    status: string;
    acknowledged: boolean;
  }[];
};
export type StaffMember = Staff;
export type Schedule = Trip;
export type ManifestPassenger = {
  passengerName: string;
  seatNumber: string;
  phone: string;
  reference: string;
};

export type ManifestStop = {
  stopId: number;
  name: string;
  latitude: number;
  longitude: number;
  stopOrder: number;
  minutesFromDeparture: number;
  pickups: ManifestPassenger[];
  dropoffs: ManifestPassenger[];
  pickupCount: number;
  dropoffCount: number;
};

export type TripTracking = {
  id: number;
  tripId: number;
  driverId?: number;
  busId?: number;
  status: string;
  isLive: boolean;
  startedAt?: string | null;
  endedAt?: string | null;
  delayMinutes: number;
  delayReason?: string | null;
  approachingStopId?: number | null;
  approachingStopName?: string | null;
  currentLatitude?: number | null;
  currentLongitude?: number | null;
  currentSpeed: number;
  currentProgress: number;
  totalPickups: number;
  totalDropoffs: number;
  lastHeartbeat: string;
};

export type Tracking = {
  trip: Trip;
  mode: string;
  gpsStatus: string;
  isLive?: boolean;
  tripTracking?: TripTracking;
  manifest?: ManifestStop[];
  position: {
    latitude: number;
    longitude: number;
    speed: number;
    progress: number;
    recordedAt: string;
  } | null;
  eta: string;
  distanceRemainingKm: number | null;
  message: string;
};
export type Dashboard = {
  todayTrips: number;
  activeBuses: number;
  totalBookings: number;
  availableSeats: number;
  delayedTrips: number;
  pendingRequests: number;
  revenue: number;
  daily: { date: string; bookings: number; revenue: number }[];
  utilization: { bus: string; trips: number; bookedSeats: number }[];
  tripStatus: Record<string, number>;
};
